# ===================================================================== #
#  An R package by Certe:                                               #
#  https://github.com/certe-medical-epidemiology                        #
#                                                                       #
#  Licensed as GPL-v2.0.                                                #
#                                                                       #
#  Developed at non-profit organisation Certe Medical Diagnostics &     #
#  Advice, department of Medical Epidemiology.                          #
#                                                                       #
#  This R package is free software; you can freely use and distribute   #
#  it for both personal and commercial purposes under the terms of the  #
#  GNU General Public License version 2.0 (GNU GPL-2), as published by  #
#  the Free Software Foundation.                                        #
#                                                                       #
#  We created this package for both routine data analysis and academic  #
#  research and it was publicly released in the hope that it will be    #
#  useful, but it comes WITHOUT ANY WARRANTY OR LIABILITY.              #
# ===================================================================== #

#' Methods for [plot2()]
#' 
#' These are the implemented methods for different S3 classes to be used in [plot2()]. Since they have an extensive list of arguments, they are placed here on a separate manual page.
#' @rdname plot2-extensions
#' @name plot2-extensions
#' @importFrom plot2 plot2
#' @inheritParams plot2::plot2
#' @details For antimicrobial resistance (AMR) data analysis, use the [`bug_drug_combinations()`][AMR::bug_drug_combinations()] or the [`sir_df()`][AMR::sir_df()] function from the `AMR` package on a data set with antibiograms. The result can be used as input for [plot2()].
#' @param minimum minimum number of results, defaults to `30`
#' @param remove_intrinsic_resistant a [logical] to indicate that rows with 100% resistance must be removed from the data set before plotting
#' @param language language to be used for antibiotic names
#' @importFrom plot2 plot2 get_colour
#' @importFrom AMR ab_name as.sir
#' @importFrom dplyr filter select mutate
#' @importFrom tidyr pivot_longer
#' @importFrom certestyle dec_mark big_mark
#' @export
plot2.bug_drug_combinations <- function(.data,
                                        x = ab,
                                        y = value,
                                        category = name,
                                        facet = mo,
                                        type = "column",
                                        x.title = FALSE,
                                        y.title = FALSE,
                                        category.title = NULL,
                                        title = NULL,
                                        subtitle = NULL,
                                        caption = NULL,
                                        tag = NULL,
                                        title.linelength = 60,
                                        title.colour = getOption("plot2.colour_font_primary", "black"),
                                        subtitle.linelength = 60,
                                        subtitle.colour = getOption("plot2.colour_font_secondary", "grey35"),
                                        na.replace = "",
                                        na.rm = FALSE,
                                        facet.position = "top",
                                        facet.fill = NULL,
                                        facet.bold = TRUE,
                                        facet.italic = FALSE,
                                        facet.size = 10,
                                        facet.margin = 8,
                                        facet.repeat_lbls_x = TRUE,
                                        facet.repeat_lbls_y = TRUE,
                                        facet.fixed_y = NULL,
                                        facet.fixed_x = TRUE,
                                        facet.drop = FALSE,
                                        facet.nrow = NULL,
                                        facet.relative = FALSE,
                                        x.date_breaks = NULL,
                                        x.date_labels = NULL,
                                        x.date_remove_years = NULL,
                                        category.focus = NULL,
                                        colour = get_colour("certe_sir2", 7),
                                        colour_fill = NULL,
                                        colour_opacity = 0,
                                        x.lbl_angle = ifelse(horizontal, 0, 90),
                                        x.lbl_align = NULL,
                                        x.lbl_italic = FALSE,
                                        x.lbl_taxonomy = TRUE,
                                        x.remove = FALSE,
                                        x.position = "bottom",
                                        x.max_items = Inf,
                                        x.max_txt = "(rest, x%n)",
                                        category.max_items = Inf,
                                        category.max_txt = "(rest, x%n)",
                                        facet.max_items = Inf,
                                        facet.max_txt = "(rest, x%n)",
                                        x.breaks = NULL,
                                        x.n_breaks = NULL,
                                        x.transform = "identity",
                                        x.expand = NULL,
                                        x.limits = NULL,
                                        x.labels = NULL,
                                        x.character = NULL,
                                        x.drop = FALSE,
                                        x.mic = FALSE,
                                        x.zoom = FALSE,
                                        y.remove = FALSE,
                                        y.24h = FALSE,
                                        y.age = FALSE,
                                        y.scientific = NULL,
                                        y.percent = FALSE,
                                        y.percent_break = 0.1,
                                        y.breaks = NULL,
                                        y.n_breaks = NULL,
                                        y.limits = NULL,
                                        y.labels = NULL,
                                        y.expand = NULL,
                                        y.transform = "identity",
                                        y.position = "left",
                                        y.zoom = FALSE,
                                        y_secondary = NULL,
                                        y_secondary.type = type,
                                        y_secondary.title = TRUE,
                                        y_secondary.colour = "certeroze",
                                        y_secondary.colour_fill = "certeroze6",
                                        y_secondary.scientific = NULL,
                                        y_secondary.percent = FALSE,
                                        y_secondary.labels = NULL,
                                        category.labels = NULL,
                                        category.percent = FALSE,
                                        category.breaks = NULL,
                                        category.limits = NULL,
                                        category.expand = 0,
                                        category.midpoint = NULL,
                                        category.transform = "identity",
                                        category.date_breaks = NULL,
                                        category.date_labels = NULL,
                                        category.character = NULL,
                                        x.sort = NULL,
                                        category.sort = FALSE,
                                        facet.sort = TRUE,
                                        x.complete = NULL,
                                        category.complete = NULL,
                                        facet.complete = NULL,
                                        datalabels = TRUE,
                                        datalabels.round = ifelse(y.percent, 2, 1),
                                        datalabels.format = "%n",
                                        datalabels.colour = "grey25",
                                        datalabels.colour_fill = NULL,
                                        datalabels.size = (3 * text_factor),
                                        datalabels.angle = 0,
                                        datalabels.lineheight = 1.0,
                                        decimal.mark = dec_mark(),
                                        big.mark = big_mark(),
                                        summarise_function = base::sum,
                                        stacked = FALSE,
                                        stackedpercent = TRUE,
                                        horizontal = TRUE,
                                        reverse = TRUE,
                                        smooth = NULL,
                                        smooth.method = NULL,
                                        smooth.formula = NULL,
                                        smooth.se = TRUE,
                                        smooth.level = 0.95,
                                        smooth.alpha = 0.25,
                                        smooth.linewidth = 0.75,
                                        smooth.linetype = 3,
                                        smooth.colour = NULL,
                                        size = NULL,
                                        linetype = 1,
                                        linewidth = NULL,
                                        binwidth = NULL,
                                        width = NULL,
                                        jitter_seed = NA,
                                        violin_scale = "count",
                                        legend.position = NULL,
                                        legend.title = NULL, # TRUE in numeric categories
                                        legend.reverse = TRUE,
                                        legend.barheight = 6,
                                        legend.barwidth = 1.5,
                                        legend.nbin = 300,
                                        legend.italic = FALSE,
                                        sankey.node_width = 0.15,
                                        sankey.node_whitespace = 0.03,
                                        sankey.alpha = 0.5,
                                        sankey.remove_axes = NULL,
                                        zoom = FALSE,
                                        sep = " / ",
                                        print = FALSE,
                                        text_factor = 1,
                                        font = getOption("plot2.font"),
                                        theme = getOption("plot2.theme", "theme_minimal2"),
                                        background = getOption("plot2.colour_background", "white"),
                                        markdown = TRUE,
                                        minimum = 30,
                                        remove_intrinsic_resistant = TRUE,
                                        language = "nl",
                                        ...) {
  
  df <- .data
  if (isTRUE(remove_intrinsic_resistant)) {
    df <- df |> 
      filter(total != R)
  }
  df <- df |> 
    filter(total >= minimum) |> 
    select(-total) |>
    mutate(ab = ab_name(ab, language = language)) |> 
    pivot_longer(-c(mo, ab)) |> 
    mutate(name = as.sir(name)) |> 
    filter(value != 0 | name %in% c("S", "I", "R"))
  
  plot2(.data = df,
        x = {{ x }},
        y = {{ y }},
        category = {{ category }},
        facet = {{ facet }},
        type = type,
        x.title = {{ x.title }},
        y.title = {{ y.title }},
        category.title = {{ category.title }},
        title = {{ title }},
        subtitle = {{ subtitle }},
        caption = {{ caption }},
        tag = {{ tag }},
        title.linelength = title.linelength,
        title.colour = title.colour,
        subtitle.linelength = subtitle.linelength,
        subtitle.colour = subtitle.colour,
        na.replace = na.replace,
        na.rm = na.rm,
        facet.position = facet.position,
        facet.fill = facet.fill,
        facet.bold = facet.bold,
        facet.italic = facet.italic,
        facet.size = facet.size,
        facet.margin = facet.margin,
        facet.repeat_lbls_x = facet.repeat_lbls_x,
        facet.repeat_lbls_y = facet.repeat_lbls_y,
        facet.fixed_y = facet.fixed_y,
        facet.fixed_x = facet.fixed_x,
        facet.drop = facet.drop,
        facet.nrow = facet.nrow,
        facet.relative = facet.relative,
        x.date_breaks = x.date_breaks,
        x.date_labels = x.date_labels,
        x.date_remove_years = x.date_remove_years,
        category.focus = category.focus,
        colour = colour,
        colour_fill = colour_fill,
        colour_opacity = colour_opacity,
        x.lbl_angle = x.lbl_angle,
        x.lbl_align = x.lbl_align,
        x.lbl_italic = x.lbl_italic,
        x.lbl_taxonomy = x.lbl_taxonomy,
        x.remove = x.remove,
        x.position = x.position,
        x.max_items = x.max_items,
        x.max_txt = x.max_txt,
        category.max_items = category.max_items,
        category.max_txt = category.max_txt,
        facet.max_items = facet.max_items,
        facet.max_txt = facet.max_txt,
        x.breaks = x.breaks,
        x.n_breaks = x.n_breaks,
        x.transform = x.transform,
        x.expand = x.expand,
        x.limits = x.limits,
        x.labels = x.labels,
        x.character = x.character,
        x.drop = x.drop,
        x.mic = x.mic,
        x.zoom = x.zoom,
        y.remove = y.remove,
        y.24h = y.24h,
        y.age = y.age,
        y.scientific = y.scientific,
        y.percent = y.percent,
        y.percent_break = y.percent_break,
        y.breaks = y.breaks,
        y.n_breaks = y.n_breaks,
        y.limits = y.limits,
        y.labels = y.labels,
        y.expand = y.expand,
        y.transform = y.transform,
        y.position = y.position,
        y.zoom = y.zoom,
        y_secondary = {{ y_secondary }},
        y_secondary.type = y_secondary.type,
        y_secondary.title = {{ y_secondary.title }},
        y_secondary.colour = y_secondary.colour,
        y_secondary.colour_fill = y_secondary.colour_fill,
        y_secondary.scientific = y_secondary.scientific,
        y_secondary.percent = y_secondary.percent,
        y_secondary.labels = y_secondary.labels,
        category.labels = category.labels,
        category.percent = category.percent,
        category.breaks = category.breaks,
        category.limits = category.limits,
        category.expand = category.expand,
        category.midpoint = category.midpoint,
        category.transform = category.transform,
        category.date_breaks = category.date_breaks,
        category.date_labels = category.date_labels,
        category.character = category.character,
        x.sort = x.sort,
        category.sort = category.sort,
        facet.sort = facet.sort,
        x.complete = x.complete,
        category.complete = category.complete,
        facet.complete = facet.complete,
        datalabels = {{ datalabels }},
        datalabels.round = datalabels.round,
        datalabels.colour = datalabels.colour,
        datalabels.format = datalabels.format,
        datalabels.colour_fill = datalabels.colour_fill,
        datalabels.size = datalabels.size,
        datalabels.angle = datalabels.angle,
        datalabels.lineheight = datalabels.lineheight,
        decimal.mark = decimal.mark,
        big.mark = big.mark,
        summarise_function = summarise_function,
        stacked = stacked,
        stackedpercent = stackedpercent,
        horizontal = horizontal,
        reverse = reverse,
        smooth = smooth,
        smooth.method = smooth.method,
        smooth.formula = smooth.formula,
        smooth.se = smooth.se,
        smooth.level = smooth.level,
        smooth.alpha = smooth.alpha,
        smooth.linewidth = smooth.linewidth,
        smooth.linetype = smooth.linetype,
        smooth.colour = smooth.colour,
        size = size,
        linetype = linetype,
        linewidth = linewidth,
        binwidth = binwidth,
        width = width,
        jitter_seed = jitter_seed,
        violin_scale = violin_scale,
        legend.position = legend.position,
        legend.title = {{ legend.title }},
        legend.reverse = legend.reverse,
        legend.barheight = legend.barheight,
        legend.barwidth = legend.barwidth,
        legend.nbin = legend.nbin,
        legend.italic = legend.italic,
        sankey.node_width = sankey.node_width,
        sankey.node_whitespace = sankey.node_whitespace,
        sankey.alpha = sankey.alpha,
        sankey.remove_axes = sankey.remove_axes,
        zoom = zoom,
        sep = sep,
        print = print,
        text_factor = text_factor,
        font = font,
        theme = theme,
        background = background,
        markdown = markdown,
        `_misses.x` = missing(x),
        `_misses.y` = missing(y),
        `_misses.category` = missing(category),
        `_misses.facet` = missing(facet),
        `_misses.datalabels` = missing(datalabels),
        `_misses.colour_fill` = missing(colour_fill),
        `_misses.x.title` = FALSE,
        `_misses.y.title` = FALSE,
        `_misses.title` = missing(title),
        `_misses.subtitle` = missing(subtitle),
        `_misses.tag` = missing(tag),
        `_misses.caption` = missing(caption),
        `_misses.y.percent` = missing(y.percent),
        `_misses.y.percent_break` = missing(y.percent_break),
        `_misses.x.zoom` = missing(x.zoom),
        `_misses.x.max_items` = missing(x.max_items),
        `_misses.facet.fixed_x` = missing(facet.fixed_x),
        `_label.x` = deparse(substitute(x)),
        `_label.y` = deparse(substitute(y)),
        `_label.category` = deparse(substitute(category)),
        `_label.facet` = deparse(substitute(facet)),
        `_label.y_secondary` = deparse(substitute(y_secondary)),
        `_summarise_fn_name` = deparse(substitute(summarise_function)),
        `_misses.summarise_function` = missing(summarise_function),
        ...) 
}

#' @rdname plot2-extensions
#' @importFrom ggplot2 aes facet_wrap geom_col ggplot labs position_dodge2
#' @importFrom dplyr mutate
#' @importFrom plot2 plot2 get_colour
#' @export
#' @examples
#' 
#' # AMR DATA ANALYSIS ----------------------------------------------------
#' if (require("AMR")) {
#'   example_isolates[, c("mo", "AMX", "AMC", "ward")] |>
#'     antibiogram(mo_transform = "gramstain",
#'                 language = "nl") |>
#'     plot2()
#' }
#' 
#' if (require("AMR")) {
#'   example_isolates[, c("mo", "AMX", "AMC", "ward")] |>
#'     antibiogram(mo_transform = "gramstain",
#'                 language = "nl",
#'                 syndromic_group = "ward") |>
#'     plot2()
#' }
plot2.antibiogram <- function(.data,
                              x = NULL,
                              y = NULL,
                              category = NULL,
                              facet = NULL,
                              type = NULL,
                              x.title = NULL,
                              y.title = NULL,
                              category.title = NULL,
                              title = NULL,
                              subtitle = NULL,
                              caption = NULL,
                              tag = NULL,
                              title.linelength = 60,
                              title.colour = getOption("plot2.colour_font_primary", "black"),
                              subtitle.linelength = 60,
                              subtitle.colour = getOption("plot2.colour_font_secondary", "grey35"),
                              na.replace = "",
                              na.rm = FALSE,
                              facet.position = "top",
                              facet.fill = NULL,
                              facet.bold = TRUE,
                              facet.italic = FALSE,
                              facet.size = 10,
                              facet.margin = 8,
                              facet.repeat_lbls_x = TRUE,
                              facet.repeat_lbls_y = TRUE,
                              facet.fixed_y = NULL,
                              facet.fixed_x = TRUE,
                              facet.drop = FALSE,
                              facet.nrow = NULL,
                              facet.relative = FALSE,
                              x.date_breaks = NULL,
                              x.date_labels = NULL,
                              x.date_remove_years = NULL,
                              category.focus = NULL,
                              colour = getOption("plot2.colour", "ggplot2"),
                              colour_fill = NULL,
                              colour_opacity = 0,
                              x.lbl_angle = 0,
                              x.lbl_align = NULL,
                              x.lbl_italic = FALSE,
                              x.lbl_taxonomy = FALSE,
                              x.remove = FALSE,
                              x.position = "bottom",
                              x.max_items = Inf,
                              x.max_txt = "(rest, x%n)",
                              category.max_items = Inf,
                              category.max_txt = "(rest, x%n)",
                              facet.max_items = Inf,
                              facet.max_txt = "(rest, x%n)",
                              x.breaks = NULL,
                              x.n_breaks = NULL,
                              x.transform = "identity",
                              x.expand = NULL,
                              x.limits = NULL,
                              x.labels = NULL,
                              x.character = NULL,
                              x.drop = FALSE,
                              x.mic = FALSE,
                              x.zoom = FALSE,
                              y.remove = FALSE,
                              y.24h = FALSE,
                              y.age = FALSE,
                              y.scientific = NULL,
                              y.percent = FALSE,
                              y.percent_break = 0.1,
                              y.breaks = NULL,
                              y.n_breaks = NULL,
                              y.limits = NULL,
                              y.labels = NULL,
                              y.expand = NULL,
                              y.transform = "identity",
                              y.position = "left",
                              y.zoom = FALSE,
                              y_secondary = NULL,
                              y_secondary.type = type,
                              y_secondary.title = TRUE,
                              y_secondary.colour = "certeroze",
                              y_secondary.colour_fill = "certeroze6",
                              y_secondary.scientific = NULL,
                              y_secondary.percent = FALSE,
                              y_secondary.labels = NULL,
                              category.labels = NULL,
                              category.percent = FALSE,
                              category.breaks = NULL,
                              category.limits = NULL,
                              category.expand = 0,
                              category.midpoint = NULL,
                              category.transform = "identity",
                              category.date_breaks = NULL,
                              category.date_labels = NULL,
                              category.character = NULL,
                              x.sort = NULL,
                              category.sort = TRUE,
                              facet.sort = TRUE,
                              x.complete = NULL,
                              category.complete = NULL,
                              facet.complete = NULL,
                              datalabels = TRUE,
                              datalabels.round = ifelse(y.percent, 2, 1),
                              datalabels.format = "%n",
                              datalabels.colour = "grey25",
                              datalabels.colour_fill = NULL,
                              datalabels.size = (3 * text_factor),
                              datalabels.angle = 0,
                              datalabels.lineheight = 1.0,
                              decimal.mark = dec_mark(),
                              big.mark = big_mark(),
                              summarise_function = base::sum,
                              stacked = FALSE,
                              stackedpercent = FALSE,
                              horizontal = FALSE,
                              reverse = horizontal,
                              smooth = NULL,
                              smooth.method = NULL,
                              smooth.formula = NULL,
                              smooth.se = TRUE,
                              smooth.level = 0.95,
                              smooth.alpha = 0.25,
                              smooth.linewidth = 0.75,
                              smooth.linetype = 3,
                              smooth.colour = NULL,
                              size = NULL,
                              linetype = 1,
                              linewidth = NULL,
                              binwidth = NULL,
                              width = NULL,
                              jitter_seed = NA,
                              violin_scale = "count",
                              legend.position = NULL,
                              legend.title = NULL, # will become TRUE in numeric categories if left NULL
                              legend.reverse = FALSE,
                              legend.barheight = 6,
                              legend.barwidth = 1.5,
                              legend.nbin = 300,
                              legend.italic = FALSE,
                              sankey.node_width = 0.15,
                              sankey.node_whitespace = 0.03,
                              sankey.alpha = 0.5,
                              sankey.remove_axes = NULL,
                              zoom = FALSE,
                              sep = " / ",
                              print = FALSE,
                              text_factor = 1,
                              font = getOption("plot2.font"),
                              theme = getOption("plot2.theme", "theme_minimal2"),
                              background = getOption("plot2.colour_background", "white"),
                              markdown = TRUE,
                              ...) {
  
  df <- attributes(.data)$long
  
  if ("syndromic_group" %in% colnames(df)) {
    geom <- geom_col(
      aes(
        x = ab,
        y = SI * 100,
        fill = if ("syndromic_group" %in% colnames(df)) {
          syndromic_group
        } else {
          NULL
        }
      ),
      position = position_dodge2(preserve = "single"))
  } else {
    geom <- geom_col(
      aes(
        x = ab,
        y = SI * 100,
      ),
      fill = get_colour(colour, length = 1),
      position = position_dodge2(preserve = "single"))
  }
  
  p <- ggplot(df) +
    geom +
    facet_wrap("mo") +
    labs(
      y = ifelse(isTRUE(attributes(.data)$combine_SI), "%SI", "%S"),
      x = NULL,
      fill = if ("syndromic_group" %in% colnames(df)) {
        colnames(.data)[1]
      } else {
        NULL
      }
    )
  
  validate_theme <- get("validate_theme", envir = asNamespace("plot2"))
  theme <- validate_theme(theme = theme,
                          type = "geom_col",
                          background = background,
                          text_factor = text_factor,
                          font = font,
                          horizontal = FALSE,
                          x.remove = NULL,
                          y.remove = NULL,
                          x.lbl_angle = 0,
                          x.lbl_align = NULL,
                          x.lbl_italic = NULL,
                          facet.fill = NULL,
                          facet.bold = NULL,
                          facet.italic = NULL,
                          facet.size = 10,
                          facet.margin = 8,
                          legend.italic = NULL,
                          sankey.remove_axes = FALSE,
                          title.colour = title.colour,
                          subtitle.colour = subtitle.colour,
                          has_y_secondary = NULL,
                          has_category = NULL,
                          col_y_primary = NULL,
                          col_y_secondary = NULL)
  
  validate_y_scale <- get("validate_y_scale", envir = asNamespace("plot2"))
  y_scale <- validate_y_scale(df = p$data |> mutate(`_var_y` = SI),
                              type = "geom_col",
                              y.24h = FALSE,
                              y.age = FALSE,
                              y.scientific = NULL,
                              y.breaks = NULL,
                              y.n_breaks = NULL,
                              y.expand = NULL,
                              y.labels = NULL,
                              y.limits = NULL,
                              y.percent = FALSE,
                              y.percent_break = 0.1,
                              misses_y.percent_break = TRUE,
                              y.position = "left",
                              y.transform = "identity",
                              y.zoom = FALSE,
                              stacked = FALSE,
                              stackedpercent = FALSE,
                              facet.fixed_y = FALSE,
                              decimal.mark = dec_mark(),
                              big.mark = big_mark(),
                              add_y_secondary = FALSE)
  
  p <- p +
    theme +
    scale_fill_certe_d(colour = colour) +
    y_scale
  
  if (!missing(x.title)) p <- p + labs(x = validate_title(x.title, markdown = markdown))
  if (!missing(y.title)) p <- p + labs(y = validate_title(y.title, markdown = markdown))
  if (!missing(title)) p <- p + labs(title = validate_title(title, markdown = markdown, max_length = title.linelength))
  if (!missing(subtitle)) p <- p + labs(subtitle = validate_title(subtitle, markdown = markdown, max_length = subtitle.linelength))
  if (!missing(tag)) p <- p + labs(tag = validate_title(tag, markdown = markdown))
  if (!missing(caption)) p <- p + labs(caption = validate_title(caption, markdown = markdown))
  
  if (isTRUE(print)) {
    print(p)
  } else {
    p
  }
}

#' @rdname plot2-extensions
#' @importFrom plot2 plot2 get_colour
#' @export
plot2.sir_df <- function(.data,
                         x = NULL,
                         y = isolates,
                         category = interpretation,
                         facet = antibiotic,
                         type = "column",
                         x.title = TRUE,
                         y.title = FALSE,
                         category.title = NULL,
                         title = FALSE,
                         subtitle = NULL,
                         caption = NULL,
                         tag = NULL,
                         title.linelength = 60,
                         title.colour = getOption("plot2.colour_font_primary", "black"),
                         subtitle.linelength = 60,
                         subtitle.colour = getOption("plot2.colour_font_secondary", "grey35"),
                         na.replace = "",
                         na.rm = FALSE,
                         facet.position = "top",
                         facet.fill = NULL,
                         facet.bold = TRUE,
                         facet.italic = FALSE,
                         facet.size = 10,
                         facet.margin = 8,
                         facet.repeat_lbls_x = TRUE,
                         facet.repeat_lbls_y = TRUE,
                         facet.fixed_y = NULL,
                         facet.fixed_x = TRUE,
                         facet.drop = FALSE,
                         facet.nrow = NULL,
                         facet.relative = FALSE,
                         x.date_breaks = NULL,
                         x.date_labels = NULL,
                         x.date_remove_years = NULL,
                         category.focus = NULL,
                         colour = get_colour("certe_sir2", 5),
                         colour_fill = NULL,
                         colour_opacity = 0,
                         x.lbl_angle = 0,
                         x.lbl_align = NULL,
                         x.lbl_italic = FALSE,
                         x.lbl_taxonomy = TRUE,
                         x.remove = FALSE,
                         x.position = "bottom",
                         x.max_items = Inf,
                         x.max_txt = "(rest, x%n)",
                         category.max_items = Inf,
                         category.max_txt = "(rest, x%n)",
                         facet.max_items = Inf,
                         facet.max_txt = "(rest, x%n)",
                         x.breaks = NULL,
                         x.n_breaks = NULL,
                         x.transform = "identity",
                         x.expand = NULL,
                         x.limits = NULL,
                         x.labels = NULL,
                         x.character = NULL,
                         x.drop = FALSE,
                         x.mic = FALSE,
                         x.zoom = FALSE,
                         y.remove = FALSE,
                         y.24h = FALSE,
                         y.age = FALSE,
                         y.scientific = NULL,
                         y.percent = FALSE,
                         y.percent_break = 0.1,
                         y.breaks = NULL,
                         y.n_breaks = NULL,
                         y.limits = NULL,
                         y.labels = NULL,
                         y.expand = NULL,
                         y.transform = "identity",
                         y.position = "left",
                         y.zoom = FALSE,
                         y_secondary = NULL,
                         y_secondary.type = type,
                         y_secondary.title = TRUE,
                         y_secondary.colour = "certeroze",
                         y_secondary.colour_fill = "certeroze6",
                         y_secondary.scientific = NULL,
                         y_secondary.percent = FALSE,
                         y_secondary.labels = NULL,
                         category.labels = NULL,
                         category.percent = FALSE,
                         category.breaks = NULL,
                         category.limits = NULL,
                         category.expand = 0,
                         category.midpoint = NULL,
                         category.transform = "identity",
                         category.date_breaks = NULL,
                         category.date_labels = NULL,
                         category.character = NULL,
                         x.sort = NULL,
                         category.sort = FALSE,
                         facet.sort = TRUE,
                         x.complete = NULL,
                         category.complete = NULL,
                         facet.complete = NULL,
                         datalabels = TRUE,
                         datalabels.round = ifelse(y.percent, 2, 1),
                         datalabels.format = "%n",
                         datalabels.colour = "grey25",
                         datalabels.colour_fill = NULL,
                         datalabels.size = (3 * text_factor),
                         datalabels.angle = 0,
                         datalabels.lineheight = 1.0,
                         decimal.mark = dec_mark(),
                         big.mark = big_mark(),
                         summarise_function = base::sum,
                         stacked = FALSE,
                         stackedpercent = TRUE,
                         horizontal = FALSE,
                         reverse = TRUE,
                         smooth = NULL,
                         smooth.method = NULL,
                         smooth.formula = NULL,
                         smooth.se = TRUE,
                         smooth.level = 0.95,
                         smooth.alpha = 0.25,
                         smooth.linewidth = 0.75,
                         smooth.linetype = 3,
                         smooth.colour = NULL,
                         size = NULL,
                         linetype = 1,
                         linewidth = NULL,
                         binwidth = NULL,
                         width = NULL,
                         jitter_seed = NA,
                         violin_scale = "count",
                         legend.position = NULL,
                         legend.title = NULL, # TRUE in numeric categories
                         legend.reverse = FALSE,
                         legend.barheight = 6,
                         legend.barwidth = 1.5,
                         legend.nbin = 300,
                         legend.italic = FALSE,
                         sankey.node_width = 0.15,
                         sankey.node_whitespace = 0.03,
                         sankey.alpha = 0.5,
                         sankey.remove_axes = NULL,
                         zoom = FALSE,
                         sep = " / ",
                         print = FALSE,
                         text_factor = 1,
                         font = getOption("plot2.font"),
                         theme = getOption("plot2.theme", "theme_minimal2"),
                         background = getOption("plot2.colour_background", "white"),
                         markdown = TRUE,
                         ...) {
  
  if (!"isolates" %in% colnames(.data) && !is.integer(.data$value)) {
    stop("isolate count not available, use AMR::sir_df() or AMR::count_df() before plotting", call. = FALSE)
  } else if (is.integer(.data$value)) {
    .data$isolates <- .data$value
  }
  
  class(.data) <- class(.data)[class(.data) != "sir_df"]
  
  plot2(.data = .data,
        x = {{ x }},
        y = {{ y }},
        category = {{ category }},
        facet = {{ facet }},
        type = type,
        x.title = {{ x.title }},
        y.title = {{ y.title }},
        category.title = {{ category.title }},
        title = {{ title }},
        subtitle = {{ subtitle }},
        caption = {{ caption }},
        tag = {{ tag }},
        title.linelength = title.linelength,
        title.colour = title.colour,
        subtitle.linelength = subtitle.linelength,
        subtitle.colour = subtitle.colour,
        na.replace = na.replace,
        na.rm = na.rm,
        facet.position = facet.position,
        facet.fill = facet.fill,
        facet.bold = facet.bold,
        facet.italic = facet.italic,
        facet.size = facet.size,
        facet.margin = facet.margin,
        facet.repeat_lbls_x = facet.repeat_lbls_x,
        facet.repeat_lbls_y = facet.repeat_lbls_y,
        facet.fixed_y = facet.fixed_y,
        facet.fixed_x = facet.fixed_x,
        facet.drop = facet.drop,
        facet.nrow = facet.nrow,
        facet.relative = facet.relative,
        x.date_breaks = x.date_breaks,
        x.date_labels = x.date_labels,
        x.date_remove_years = x.date_remove_years,
        category.focus = category.focus,
        colour = colour,
        colour_fill = colour_fill,
        colour_opacity = colour_opacity,
        x.lbl_angle = x.lbl_angle,
        x.lbl_align = x.lbl_align,
        x.lbl_italic = x.lbl_italic,
        x.lbl_taxonomy = x.lbl_taxonomy,
        x.remove = x.remove,
        x.position = x.position,
        x.max_items = x.max_items,
        x.max_txt = x.max_txt,
        category.max_items = category.max_items,
        category.max_txt = category.max_txt,
        facet.max_items = facet.max_items,
        facet.max_txt = facet.max_txt,
        x.breaks = x.breaks,
        x.n_breaks = x.n_breaks,
        x.transform = x.transform,
        x.expand = x.expand,
        x.limits = x.limits,
        x.labels = x.labels,
        x.character = x.character,
        x.drop = x.drop,
        x.mic = x.mic,
        x.zoom = x.zoom,
        y.remove = y.remove,
        y.24h = y.24h,
        y.age = y.age,
        y.scientific = y.scientific,
        y.percent = y.percent,
        y.percent_break = y.percent_break,
        y.breaks = y.breaks,
        y.n_breaks = y.n_breaks,
        y.limits = y.limits,
        y.labels = y.labels,
        y.expand = y.expand,
        y.transform = y.transform,
        y.position = y.position,
        y.zoom = y.zoom,
        y_secondary = {{ y_secondary }},
        y_secondary.type = y_secondary.type,
        y_secondary.title = {{ y_secondary.title }},
        y_secondary.colour = y_secondary.colour,
        y_secondary.colour_fill = y_secondary.colour_fill,
        y_secondary.scientific = y_secondary.scientific,
        y_secondary.percent = y_secondary.percent,
        y_secondary.labels = y_secondary.labels,
        category.labels = category.labels,
        category.percent = category.percent,
        category.breaks = category.breaks,
        category.limits = category.limits,
        category.expand = category.expand,
        category.midpoint = category.midpoint,
        category.transform = category.transform,
        category.date_breaks = category.date_breaks,
        category.date_labels = category.date_labels,
        category.character = category.character,
        x.sort = x.sort,
        category.sort = category.sort,
        facet.sort = facet.sort,
        x.complete = x.complete,
        category.complete = category.complete,
        facet.complete = facet.complete,
        datalabels = {{ datalabels }},
        datalabels.round = datalabels.round,
        datalabels.colour = datalabels.colour,
        datalabels.format = datalabels.format,
        datalabels.colour_fill = datalabels.colour_fill,
        datalabels.size = datalabels.size,
        datalabels.angle = datalabels.angle,
        datalabels.lineheight = datalabels.lineheight,
        decimal.mark = decimal.mark,
        big.mark = big.mark,
        summarise_function = summarise_function,
        stacked = stacked,
        stackedpercent = stackedpercent,
        horizontal = horizontal,
        reverse = reverse,
        smooth = smooth,
        smooth.method = smooth.method,
        smooth.formula = smooth.formula,
        smooth.se = smooth.se,
        smooth.level = smooth.level,
        smooth.alpha = smooth.alpha,
        smooth.linewidth = smooth.linewidth,
        smooth.linetype = smooth.linetype,
        smooth.colour = smooth.colour,
        size = size,
        linetype = linetype,
        linewidth = linewidth,
        binwidth = binwidth,
        width = width,
        jitter_seed = jitter_seed,
        violin_scale = violin_scale,
        legend.position = legend.position,
        legend.title = {{ legend.title }},
        legend.reverse = legend.reverse,
        legend.barheight = legend.barheight,
        legend.barwidth = legend.barwidth,
        legend.nbin = legend.nbin,
        legend.italic = legend.italic,
        sankey.node_width = sankey.node_width,
        sankey.node_whitespace = sankey.node_whitespace,
        sankey.alpha = sankey.alpha,
        sankey.remove_axes = sankey.remove_axes,
        zoom = zoom,
        sep = sep,
        print = print,
        text_factor = text_factor,
        font = font,
        theme = theme,
        background = background,
        markdown = markdown,
        `_misses.x` = missing(x),
        `_misses.y` = missing(y),
        `_misses.category` = missing(category),
        `_misses.facet` = missing(facet),
        `_misses.datalabels` = missing(datalabels),
        `_misses.colour_fill` = missing(colour_fill),
        `_misses.x.title` = FALSE,
        `_misses.y.title` = FALSE,
        `_misses.title` = missing(title) && !isFALSE(title),
        `_misses.subtitle` = missing(subtitle),
        `_misses.tag` = missing(tag),
        `_misses.caption` = missing(caption),
        `_misses.y.percent` = missing(y.percent),
        `_misses.y.percent_break` = missing(y.percent_break),
        `_misses.x.zoom` = missing(x.zoom),
        `_misses.x.max_items` = missing(x.max_items),
        `_misses.facet.fixed_x` = missing(facet.fixed_x),
        `_label.x` = deparse(substitute(x)),
        `_label.y` = deparse(substitute(y)),
        `_label.category` = deparse(substitute(category)),
        `_label.facet` = deparse(substitute(facet)),
        `_label.y_secondary` = deparse(substitute(y_secondary)),
        `_summarise_fn_name` = deparse(substitute(summarise_function)),
        `_misses.summarise_function` = missing(summarise_function),
        ...) 
}

#' @rdname plot2-extensions
#' @importFrom ggplot2 geom_hline geom_point geom_line element_text theme
#' @importFrom plot2 plot2 get_colour
#' @details The QC-test can be acquired with [certestats::qc_test()]. It applies the Nelson QC rules for a vector of values.
#' @export
plot2.qc_test <- function(.data,
                          x = x,
                          y = y,
                          category = rule,
                          facet = NULL,
                          type = "point",
                          x.title = "Index",
                          y.title = "Value",
                          category.title = NULL,
                          title = paste0("QC Chart (", attributes(.data)$guideline, ")"),
                          subtitle = NULL,
                          caption = NULL,
                          tag = NULL,
                          title.linelength = 60,
                          title.colour = getOption("plot2.colour_font_primary", "black"),
                          subtitle.linelength = 60,
                          subtitle.colour = getOption("plot2.colour_font_secondary", "grey35"),
                          na.replace = "",
                          na.rm = FALSE,
                          facet.position = "top",
                          facet.fill = NULL,
                          facet.bold = TRUE,
                          facet.italic = FALSE,
                          facet.size = 10,
                          facet.margin = 8,
                          facet.repeat_lbls_x = TRUE,
                          facet.repeat_lbls_y = TRUE,
                          facet.fixed_y = NULL,
                          facet.fixed_x = TRUE,
                          facet.drop = FALSE,
                          facet.nrow = NULL,
                          facet.relative = FALSE,
                          x.date_breaks = NULL,
                          x.date_labels = NULL,
                          x.date_remove_years = NULL,
                          category.focus = NULL,
                          colour = get_colour(c("Observation" = "grey75",
                                                "Rule 1" = "certeblauw",
                                                "Rule 2" = "certegroen",
                                                "Rule 3" = "certeroze",
                                                "Rule 4" = "certegeel",
                                                "Rule 5" = "certelila",
                                                "Rule 6" = "certebruin",
                                                "Rule 7" = "certeblauw2",
                                                "Rule 8" = "certegroen2")),
                          colour_fill = NULL,
                          colour_opacity = 0,
                          x.lbl_angle = 0,
                          x.lbl_align = NULL,
                          x.lbl_italic = FALSE,
                          x.lbl_taxonomy = FALSE,
                          x.remove = FALSE,
                          x.position = "bottom",
                          x.max_items = Inf,
                          x.max_txt = "(rest, x%n)",
                          category.max_items = Inf,
                          category.max_txt = "(rest, x%n)",
                          facet.max_items = Inf,
                          facet.max_txt = "(rest, x%n)",
                          x.breaks = NULL,
                          x.n_breaks = NULL,
                          x.transform = "identity",
                          x.expand = NULL,
                          x.limits = NULL,
                          x.labels = NULL,
                          x.character = NULL,
                          x.drop = FALSE,
                          x.mic = FALSE,
                          x.zoom = TRUE,
                          y.remove = FALSE,
                          y.24h = FALSE,
                          y.age = FALSE,
                          y.scientific = NULL,
                          y.percent = FALSE,
                          y.percent_break = 0.1,
                          y.breaks = NULL,
                          y.n_breaks = NULL,
                          y.limits = NULL,
                          y.labels = NULL,
                          y.expand = NULL,
                          y.transform = "identity",
                          y.position = "left",
                          y.zoom = TRUE,
                          y_secondary = NULL,
                          y_secondary.type = type,
                          y_secondary.title = TRUE,
                          y_secondary.colour = "certeroze",
                          y_secondary.colour_fill = "certeroze6",
                          y_secondary.scientific = NULL,
                          y_secondary.percent = FALSE,
                          y_secondary.labels = NULL,
                          category.labels = NULL,
                          category.percent = FALSE,
                          category.breaks = NULL,
                          category.limits = NULL,
                          category.expand = 0,
                          category.midpoint = NULL,
                          category.transform = "identity",
                          category.date_breaks = NULL,
                          category.date_labels = NULL,
                          category.character = NULL,
                          x.sort = NULL,
                          category.sort = TRUE,
                          facet.sort = TRUE,
                          x.complete = NULL,
                          category.complete = NULL,
                          facet.complete = NULL,
                          datalabels = TRUE,
                          datalabels.round = ifelse(y.percent, 2, 1),
                          datalabels.format = "%n",
                          datalabels.colour = "grey25",
                          datalabels.colour_fill = NULL,
                          datalabels.size = (3 * text_factor),
                          datalabels.angle = 0,
                          datalabels.lineheight = 1.0,
                          decimal.mark = dec_mark(),
                          big.mark = big_mark(),
                          summarise_function = base::sum,
                          stacked = FALSE,
                          stackedpercent = FALSE,
                          horizontal = FALSE,
                          reverse = horizontal,
                          smooth = NULL,
                          smooth.method = NULL,
                          smooth.formula = NULL,
                          smooth.se = TRUE,
                          smooth.level = 0.95,
                          smooth.alpha = 0.25,
                          smooth.linewidth = 0.75,
                          smooth.linetype = 3,
                          smooth.colour = NULL,
                          size = 2,
                          linetype = 1,
                          linewidth = NULL,
                          binwidth = NULL,
                          width = NULL,
                          jitter_seed = NA,
                          violin_scale = "count",
                          legend.position = "right",
                          legend.title = NULL, # TRUE in numeric categories
                          legend.reverse = FALSE,
                          legend.barheight = 6,
                          legend.barwidth = 1.5,
                          legend.nbin = 300,
                          legend.italic = FALSE,
                          sankey.node_width = 0.15,
                          sankey.node_whitespace = 0.03,
                          sankey.alpha = 0.5,
                          sankey.remove_axes = NULL,
                          zoom = TRUE,
                          sep = " / ",
                          print = FALSE,
                          text_factor = 1,
                          font = getOption("plot2.font"),
                          theme = getOption("plot2.theme", "theme_minimal2"),
                          background = getOption("plot2.colour_background", "white"),
                          markdown = TRUE,
                          ...) {
  
  loadNamespace("certestats") # will throw an error if not installed
  
  att <- attributes(.data)
  df <- data.frame(x = seq_len(length(att$values)),
                   y = att$values,
                   rule = "Observation",
                   shp = 4,
                   size = size,
                   stringsAsFactors = FALSE)
  for (i in seq_len(length(.data))) {
    if (length(.data[[i]]) > 0) {
      # only add the first here
      df_rule <- data.frame(x = .data[[i]],
                            y = att$values[.data[[i]]],
                            rule = paste0("Rule ", gsub("[^0-9]", "", names(.data)[i])),
                            shp = 13,
                            size = size * 1.5,
                            stringsAsFactors = FALSE)
      df <- rbind(df, df_rule)
    }
  }
  
  df <- df[order(df$x, df$rule), , drop = FALSE]
  
  if (missing(caption)) {
    # fill caption with rules
    rules <- names(.data[unlist(lapply(.data, function(r) length(r) > 0))])
    rules <- as.integer(gsub("[^0-9]", "", rules))
    threshold <- att$threshold[rules]
    caption <- "\n"
    for (i in seq_len(length(rules))) {
      rule <- paste0("Rule ", rules[i], ":")
      caption <- c(caption, 
                   paste(rule, certestats::qc_rule_text(rules[i], threshold[i])))
    }
    caption <- paste0(caption, collapse = "\n")
  }
  
  p <- plot2(.data = df,
             x = x,
             y = y,
             category = category,
             facet = facet,
             type = "blank",
             x.title = {{ x.title }},
             y.title = {{ y.title }},
             category.title = {{ category.title }},
             title = {{ title }},
             subtitle = {{ subtitle }},
             caption = {{ caption }},
             tag = {{ tag }},
             title.linelength = title.linelength,
             title.colour = title.colour,
             subtitle.linelength = subtitle.linelength,
             subtitle.colour = subtitle.colour,
             na.replace = na.replace,
             na.rm = na.rm,
             facet.position = facet.position,
             facet.fill = facet.fill,
             facet.bold = facet.bold,
             facet.italic = facet.italic,
             facet.size = facet.size,
             facet.margin = facet.margin,
             facet.repeat_lbls_x = facet.repeat_lbls_x,
             facet.repeat_lbls_y = facet.repeat_lbls_y,
             facet.fixed_y = facet.fixed_y,
             facet.fixed_x = facet.fixed_x,
             facet.drop = facet.drop,
             facet.nrow = facet.nrow,
             facet.relative = facet.relative,
             x.date_breaks = x.date_breaks,
             x.date_labels = x.date_labels,
             x.date_remove_years = x.date_remove_years,
             category.focus = category.focus,
             colour = colour,
             colour_fill = colour_fill,
             colour_opacity = colour_opacity,
             x.lbl_angle = x.lbl_angle,
             x.lbl_align = x.lbl_align,
             x.lbl_italic = x.lbl_italic,
             x.lbl_taxonomy = x.lbl_taxonomy,
             x.remove = x.remove,
             x.position = x.position,
             x.max_items = x.max_items,
             x.max_txt = x.max_txt,
             category.max_items = category.max_items,
             category.max_txt = category.max_txt,
             facet.max_items = facet.max_items,
             facet.max_txt = facet.max_txt,
             x.breaks = x.breaks,
             x.n_breaks = x.n_breaks,
             x.transform = x.transform,
             x.expand = x.expand,
             x.limits = x.limits,
             x.labels = x.labels,
             x.character = x.character,
             x.drop = x.drop,
             x.mic = x.mic,
             x.zoom = x.zoom,
             y.remove = y.remove,
             y.24h = y.24h,
             y.age = y.age,
             y.scientific = y.scientific,
             y.percent = y.percent,
             y.percent_break = y.percent_break,
             y.breaks = y.breaks,
             y.n_breaks = y.n_breaks,
             y.limits = y.limits,
             y.labels = y.labels,
             y.expand = y.expand,
             y.transform = y.transform,
             y.position = y.position,
             y.zoom = y.zoom,
             y_secondary = NULL,
             y_secondary.type = NULL,
             y_secondary.title = TRUE,
             y_secondary.colour = NULL,
             y_secondary.colour_fill = NULL,
             y_secondary.scientific = NULL,
             y_secondary.percent = NULL,
             y_secondary.labels = NULL,
             category.labels = category.labels,
             category.percent = category.percent,
             category.breaks = category.breaks,
             category.limits = category.limits,
             category.expand = category.expand,
             category.midpoint = category.midpoint,
             category.transform = category.transform,
             category.date_breaks = category.date_breaks,
             category.date_labels = category.date_labels,
             category.character = category.character,
             x.sort = x.sort,
             category.sort = category.sort,
             facet.sort = facet.sort,
             x.complete = x.complete,
             category.complete = category.complete,
             facet.complete = facet.complete,
             datalabels = {{ datalabels }},
             datalabels.round = datalabels.round,
             datalabels.colour = datalabels.colour,
             datalabels.format = datalabels.format,
             datalabels.colour_fill = datalabels.colour_fill,
             datalabels.size = datalabels.size,
             datalabels.angle = datalabels.angle,
             datalabels.lineheight = datalabels.lineheight,
             decimal.mark = decimal.mark,
             big.mark = big.mark,
             summarise_function = summarise_function,
             stacked = stacked,
             stackedpercent = stackedpercent,
             horizontal = horizontal,
             reverse = reverse,
             smooth = smooth,
             smooth.method = smooth.method,
             smooth.formula = smooth.formula,
             smooth.se = smooth.se,
             smooth.level = smooth.level,
             smooth.alpha = smooth.alpha,
             smooth.linewidth = smooth.linewidth,
             smooth.linetype = smooth.linetype,
             smooth.colour = smooth.colour,
             size = size,
             linetype = linetype,
             linewidth = linewidth,
             binwidth = binwidth,
             width = width,
             jitter_seed = jitter_seed,
             violin_scale = violin_scale,
             legend.position = legend.position,
             legend.title = {{ legend.title }},
             legend.reverse = legend.reverse,
             legend.barheight = legend.barheight,
             legend.barwidth = legend.barwidth,
             legend.nbin = legend.nbin,
             legend.italic = legend.italic,
             sankey.node_width = sankey.node_width,
             sankey.node_whitespace = sankey.node_whitespace,
             sankey.alpha = sankey.alpha,
             sankey.remove_axes = sankey.remove_axes,
             zoom = zoom,
             sep = sep,
             print = FALSE,
             text_factor = text_factor,
             font = font,
             theme = theme,
             background = background,
             markdown = markdown,
             `_misses.x` = FALSE,
             `_misses.y` = FALSE,
             `_misses.category` = FALSE,
             `_misses.facet` = missing(facet),
             `_misses.datalabels` = missing(datalabels),
             `_misses.colour_fill` = missing(colour_fill),
             `_misses.x.title` = FALSE,
             `_misses.y.title` = FALSE,
             `_misses.title` = FALSE,
             `_misses.subtitle` = missing(subtitle),
             `_misses.tag` = missing(tag),
             `_misses.caption` = FALSE,
             `_misses.y.percent` = missing(y.percent),
             `_misses.y.percent_break` = missing(y.percent_break),
             `_misses.x.zoom` = missing(x.zoom),
             `_misses.x.max_items` = missing(x.max_items),
             `_misses.facet.fixed_x` = missing(facet.fixed_x),
             `_label.x` = deparse(substitute(x)),
             `_label.y` = deparse(substitute(y)),
             `_label.category` = deparse(substitute(category)),
             `_label.facet` = deparse(substitute(facet)),
             `_label.y_secondary` = deparse(substitute(y_secondary)),
             `_summarise_fn_name` = deparse(substitute(summarise_function)),
             `_misses.summarise_function` = missing(summarise_function),
             ...)
  
  # left align the rule texts
  p <- p + theme(plot.caption = element_text(hjust = 0))
  
  # add reference lines
  p <- p +
    geom_hline(yintercept = mean(att$values),
               colour = "black", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) + stats::sd(att$values),
               colour = "#61D04F", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) - stats::sd(att$values),
               colour = "#61D04F", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) + 2 * stats::sd(att$values),
               colour = "#F5C710", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) - 2 * stats::sd(att$values),
               colour = "#F5C710", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) + 3 * stats::sd(att$values),
               colour = "#DF536B", linetype = 2, linewidth = linewidth) +
    geom_hline(yintercept = mean(att$values) - 3 * stats::sd(att$values),
               colour = "#DF536B", linetype = 2, linewidth = linewidth)
  
  p <- p +
    geom_point(shape = df$shp, size = df$size)
  
  # add lines for each rule found
  for (i in seq_len(length(.data))) {
    if (length(.data[[i]]) > 0) {
      threshold <- att$threshold[i]
      ind <- .data[[i]]
      p <- p +
        geom_point(data = data.frame(x = ind,
                                     y = att$values[ind]),
                   mapping = aes(x = x, y = y),
                   inherit.aes = FALSE,
                   alpha = 0.33,
                   size = size * 2.5,
                   colour = colour[i + 1])
      if (threshold > 1) {
        # print coloured lines and point for the rules
        for (j in seq_len(length(ind))) {
          ind_vector <- c(ind[j]:(ind[j] + threshold - 1))
          val <- att$values[ind_vector]
          p <- p +
            geom_line(data = data.frame(x = ind_vector,
                                        y = val),
                      mapping = aes(x = x, y = y),
                      inherit.aes = FALSE,
                      linetype = linetype,
                      linewidth = linewidth,
                      colour = colour[i + 1]) +
            geom_point(data = data.frame(x = ind_vector,
                                         y = val),
                       mapping = aes(x = x, y = y),
                       inherit.aes = FALSE,
                       shape = 4,
                       size = size,
                       colour = colour[i + 1])
        }
      }
    }
  }
  if (isTRUE(print)) {
    print(p)
  } else {
    p
  }
}

#' @rdname plot2-extensions
#' @importFrom dplyr group_by mutate ungroup summarise n_distinct `%>%` filter left_join
#' @importFrom ggplot2 geom_point aes unit
#' @importFrom plot2 add_type add_line plot2 get_colour
#' @importFrom certestyle format2
#' @details The detection of [disease clusters](https://en.wikipedia.org/wiki/Disease_cluster) can be done using [certestats::early_warning_cluster()]. Use `size` to alter the size of the triangles that indicate clusters.
#' @export
#' @examples
#' 
#' # DISEASE CLUSTERS -----------------------------------------------------
#' cases <- data.frame(date = sample(seq(as.Date("2015-01-01"),
#'                                       as.Date("2022-12-31"),
#'                                       "1 day"),
#'                                   size = 300),
#'                     patient = sample(LETTERS, size = 300, replace = TRUE))
#' check <- certestats::early_warning_cluster(cases,
#'                                            minimum_cases = 1,
#'                                            threshold_percentile = 0.75)
#' 
#' check |> plot2()
plot2.early_warning_cluster <- function(.data,
                                        x = NULL,
                                        y = NULL,
                                        category = NULL,
                                        facet = NULL,
                                        type = "line",
                                        x.title = ifelse(attributes(.data)$period_length_months == 12, "Maand in periode", "Week in periode"),
                                        y.title = paste0("Cases (", attributes(.data)$moving_average_days, "-daags zwevend gemiddelde)"),
                                        category.title = "Periode",
                                        title = paste0(n_distinct(.data$clusters$cluster), " cluster", ifelse(n_distinct(.data$clusters$cluster) != 1, "s", "")),
                                        subtitle = NULL,
                                        caption = paste0("O.b.v. uitbijter-vrije geschiedenis (coeff = ",
                                                         format2(attributes(.data)$remove_outliers_coefficient),
                                                         ") met pct = ",
                                                         format2(attributes(.data)$threshold_percentile)),
                                        tag = NULL,
                                        title.linelength = 60,
                                        title.colour = getOption("plot2.colour_font_primary", "black"),
                                        subtitle.linelength = 60,
                                        subtitle.colour = getOption("plot2.colour_font_secondary", "grey35"),
                                        na.replace = "",
                                        na.rm = FALSE,
                                        facet.position = "top",
                                        facet.fill = NULL,
                                        facet.bold = TRUE,
                                        facet.italic = FALSE,
                                        facet.size = 10,
                                        facet.margin = 8,
                                        facet.repeat_lbls_x = TRUE,
                                        facet.repeat_lbls_y = TRUE,
                                        facet.fixed_y = NULL,
                                        facet.fixed_x = TRUE,
                                        facet.drop = FALSE,
                                        facet.nrow = NULL,
                                        facet.relative = FALSE,
                                        x.date_breaks = "1 month",
                                        x.date_labels = "mmm",
                                        x.date_remove_years = FALSE, # has no impact anyway, see below at x.date_remove_years
                                        category.focus = NULL,
                                        colour = getOption("plot2.colour", "ggplot2"),
                                        colour_fill = NULL,
                                        colour_opacity = 0,
                                        x.lbl_angle = 0,
                                        x.lbl_align = NULL,
                                        x.lbl_italic = FALSE,
                                        x.lbl_taxonomy = FALSE,
                                        x.remove = FALSE,
                                        x.position = "bottom",
                                        x.max_items = Inf,
                                        x.max_txt = "(rest, x%n)",
                                        category.max_items = Inf,
                                        category.max_txt = "(rest, x%n)",
                                        facet.max_items = Inf,
                                        facet.max_txt = "(rest, x%n)",
                                        x.breaks = seq(0, 9999, 14),
                                        x.n_breaks = NULL,
                                        x.transform = "identity",
                                        x.expand = NULL,
                                        x.limits = NULL,
                                        x.labels = function(x) x / 7,
                                        x.character = NULL,
                                        x.drop = FALSE,
                                        x.mic = FALSE,
                                        x.zoom = FALSE,
                                        y.remove = FALSE,
                                        y.24h = FALSE,
                                        y.age = FALSE,
                                        y.scientific = NULL,
                                        y.percent = FALSE,
                                        y.percent_break = 0.1,
                                        y.breaks = NULL,
                                        y.n_breaks = NULL,
                                        y.limits = NULL,
                                        y.labels = NULL,
                                        y.expand = NULL,
                                        y.transform = "identity",
                                        y.position = "left",
                                        y.zoom = FALSE,
                                        y_secondary = NULL,
                                        y_secondary.type = type,
                                        y_secondary.title = TRUE,
                                        y_secondary.colour = "certeroze",
                                        y_secondary.colour_fill = "certeroze6",
                                        y_secondary.scientific = NULL,
                                        y_secondary.percent = FALSE,
                                        y_secondary.labels = NULL,
                                        category.labels = md_to_expression,
                                        category.percent = FALSE,
                                        category.breaks = NULL,
                                        category.limits = NULL,
                                        category.expand = 0,
                                        category.midpoint = NULL,
                                        category.transform = "identity",
                                        category.date_breaks = NULL,
                                        category.date_labels = NULL,
                                        category.character = TRUE,
                                        x.sort = NULL,
                                        category.sort = "asc",
                                        facet.sort = TRUE,
                                        x.complete = NULL,
                                        category.complete = NULL,
                                        facet.complete = NULL,
                                        datalabels = TRUE,
                                        datalabels.round = ifelse(y.percent, 2, 1),
                                        datalabels.format = "%n",
                                        datalabels.colour = "grey25",
                                        datalabels.colour_fill = NULL,
                                        datalabels.size = (2.5 * text_factor),
                                        datalabels.angle = 0,
                                        datalabels.lineheight = 1.0,
                                        decimal.mark = dec_mark(),
                                        big.mark = big_mark(),
                                        summarise_function = base::sum,
                                        stacked = FALSE,
                                        stackedpercent = FALSE,
                                        horizontal = FALSE,
                                        reverse = horizontal,
                                        smooth = NULL,
                                        smooth.method = NULL,
                                        smooth.formula = NULL,
                                        smooth.se = TRUE,
                                        smooth.level = 0.95,
                                        smooth.alpha = 0.25,
                                        smooth.linewidth = 0.75,
                                        smooth.linetype = 3,
                                        smooth.colour = NULL,
                                        size = NULL,
                                        linetype = 1,
                                        linewidth = NULL,
                                        binwidth = NULL,
                                        width = NULL,
                                        jitter_seed = NA,
                                        violin_scale = "count",
                                        legend.position = "right",
                                        legend.title = NULL, # TRUE in numeric categories
                                        legend.reverse = FALSE,
                                        legend.barheight = 6,
                                        legend.barwidth = 1.5,
                                        legend.nbin = 300,
                                        legend.italic = FALSE,
                                        sankey.node_width = 0.15,
                                        sankey.node_whitespace = 0.03,
                                        sankey.alpha = 0.5,
                                        sankey.remove_axes = NULL,
                                        zoom = FALSE,
                                        sep = " / ",
                                        print = FALSE,
                                        text_factor = 1,
                                        font = getOption("plot2.font"),
                                        theme = getOption("plot2.theme", "theme_minimal2"),
                                        background = getOption("plot2.colour_background", "white"),
                                        markdown = TRUE,
                                        ...) {
  loadNamespace("certestats") # will throw an error if not installed
  
  early_warning_object <- .data
  
  if (NROW(early_warning_object$details) == 0) {
    # check if markdown is required
    markdown <- validate_markdown(markdown, x.title, y.title, c(category.title, legend.title), title, subtitle, tag, caption)
    plot2_warning("No observations, returning an empty plot")
    validate_theme <- get("validate_theme", envir = asNamespace("plot2"))
    p <- ggplot() +
      validate_theme(theme = theme,
                     type = "",
                     background = background,
                     text_factor = text_factor,
                     font = font,
                     horizontal = horizontal,
                     x.remove = x.remove,
                     y.remove = y.remove,
                     x.lbl_angle = x.lbl_angle,
                     x.lbl_align = x.lbl_align,
                     x.lbl_italic = x.lbl_italic,
                     facet.fill = facet.fill,
                     facet.bold = facet.bold,
                     facet.italic = facet.italic,
                     facet.size = facet.size,
                     facet.margin = facet.margin,
                     legend.italic = legend.italic,
                     sankey.remove_axes = sankey.remove_axes,
                     title.colour = title.colour,
                     subtitle.colour = subtitle.colour,
                     has_y_secondary = FALSE,
                     col_y_primary = NULL,
                     col_y_secondary = NULL)
    if (!missing(x.title)) p <- p + labs(x = validate_title(x.title, markdown = markdown))
    if (!missing(y.title)) p <- p + labs(y = validate_title(y.title, markdown = markdown))
    if (!missing(title)) p <- p + labs(title = validate_title(title, markdown = markdown, max_length = title.linelength))
    if (!missing(subtitle)) p <- p + labs(subtitle = validate_title(subtitle, markdown = markdown, max_length = subtitle.linelength))
    if (!missing(tag)) p <- p + labs(tag = validate_title(tag, markdown = markdown))
    if (!missing(caption)) p <- p + labs(caption = validate_title(caption, markdown = markdown))
    if (isTRUE(print)) {
      print(p)
    } else {
      return(p)
    }
  }
  
  if (NROW(early_warning_object$clusters) == 0) {
    if (attributes(early_warning_object)$period_length_months == 12) {
      # plot as years
      clusters <- data.frame(cluster = integer(0), xmin = Sys.Date()[0], xmax = Sys.Date()[0])
    } else {
      # plot as days in period
      clusters <- data.frame(cluster = integer(0), xmin = double(0), xmax = double(0))
    }
  } else {
    if (attributes(early_warning_object)$period_length_months == 12) {
      # plot as years
      clusters <- early_warning_object$clusters |>
        left_join(early_warning_object$details |>
                    select(date, period_date),
                  by = "date") |> 
        group_by(cluster) |>
        summarise(xmin = min(period_date, na.rm = TRUE),
                  xmax = max(period_date, na.rm = TRUE),
                  n_cases = sum(cases, na.rm = TRUE))
    } else {
      # plot as days in period
      clusters <- early_warning_object$clusters |>
        group_by(cluster) |>
        summarise(xmin = min(day_in_period, na.rm = TRUE),
                  xmax = max(day_in_period, na.rm = TRUE),
                  n_cases = sum(cases, na.rm = TRUE))
    }
  }
  
  if (identical(colour, "certe")) {
    colour <- c("certeblauw", get_colour("greyscale", n_distinct(early_warning_object$details$period) - 1))
    if (isTRUE(attributes(early_warning_object)$based_on_historic_maximum)) {
      colour <- c(colour, "certeroze2")
    }
  } else {
    # set number of colours needed
    if (isTRUE(attributes(early_warning_object)$based_on_historic_maximum)) {
      colour <- get_colour(colour, n_distinct(early_warning_object$details$period) + 1)
    } else {
      colour <- get_colour(colour, n_distinct(early_warning_object$details$period))
    }
  }
  
  early_warning_object$details <- early_warning_object$details |>
    group_by(period = abs(period)) |>
    mutate(period_txt = paste0("**Periode ", abs(period), ":** ", format2(min(date), "d mmm \u2019yy"), " - ", format2(max(date), "d mmm \u2019yy"))) |>
    ungroup()
  
  p <- early_warning_object$details |> 
    plot2(x = if (attributes(early_warning_object)$period_length_months == 12) period_date else day_in_period,
          y = moving_avg,
          category = period_txt,
          # facet = {{facet}},
          type = type,
          x.title = x.title,
          y.title = y.title,
          category.title = category.title,
          title = title,
          subtitle = subtitle,
          caption = caption,
          tag = tag,
          title.linelength = title.linelength,
          title.colour = title.colour,
          subtitle.linelength = subtitle.linelength,
          subtitle.colour = subtitle.colour,
          na.replace = na.replace,
          na.rm = na.rm,
          facet.position = facet.position,
          facet.fill = facet.fill,
          facet.bold = facet.bold,
          facet.italic = facet.italic,
          facet.size = facet.size,
          facet.margin = facet.margin,
          facet.repeat_lbls_x = facet.repeat_lbls_x,
          facet.repeat_lbls_y = facet.repeat_lbls_y,
          facet.fixed_y = facet.fixed_y,
          facet.fixed_x = facet.fixed_x,
          facet.drop = facet.drop,
          facet.nrow = facet.nrow,
          facet.relative = facet.relative,
          x.date_breaks = x.date_breaks,
          x.date_labels = x.date_labels,
          x.date_remove_years = FALSE, # otherwise the diease cluster years will be 1970 (as plot2() works like that in unify_years())
          category.focus = category.focus,
          colour = colour,
          colour_fill = colour_fill,
          colour_opacity = colour_opacity,
          x.lbl_angle = x.lbl_angle,
          x.lbl_align = x.lbl_align,
          x.lbl_italic = x.lbl_italic,
          x.lbl_taxonomy = x.lbl_taxonomy,
          x.remove = x.remove,
          x.position = x.position,
          x.max_items = x.max_items,
          x.max_txt = x.max_txt,
          category.max_items = category.max_items,
          category.max_txt = category.max_txt,
          facet.max_items = facet.max_items,
          facet.max_txt = facet.max_txt,
          x.breaks = x.breaks,
          x.n_breaks = x.n_breaks,
          x.transform = x.transform,
          x.expand = x.expand,
          x.limits = x.limits,
          x.labels = x.labels,
          x.character = x.character,
          x.drop = x.drop,
          x.mic = x.mic,
          x.zoom = x.zoom,
          y.remove = y.remove,
          y.24h = y.24h,
          y.age = y.age,
          y.scientific = y.scientific,
          y.percent = y.percent,
          y.percent_break = y.percent_break,
          y.breaks = y.breaks,
          y.n_breaks = y.n_breaks,
          y.limits = y.limits,
          y.labels = y.labels,
          y.expand = y.expand,
          y.transform = y.transform,
          y.position = y.position,
          y.zoom = y.zoom,
          y_secondary = y_secondary,
          y_secondary.type = y_secondary.type,
          y_secondary.title = y_secondary.title,
          y_secondary.colour = y_secondary.colour,
          y_secondary.colour_fill = y_secondary.colour_fill,
          y_secondary.scientific = y_secondary.scientific,
          y_secondary.percent = y_secondary.percent,
          y_secondary.labels = y_secondary.labels,
          category.labels = category.labels,
          category.percent = category.percent,
          category.breaks = category.breaks,
          category.limits = category.limits,
          category.expand = category.expand,
          category.midpoint = category.midpoint,
          category.transform = category.transform,
          category.date_breaks = category.date_breaks,
          category.date_labels = category.date_labels,
          category.character = category.character,
          x.sort = x.sort,
          category.sort = category.sort,
          facet.sort = facet.sort,
          x.complete = x.complete,
          category.complete = category.complete,
          facet.complete = facet.complete,
          datalabels = datalabels,
          datalabels.round = datalabels.round,
          datalabels.format = datalabels.format,
          datalabels.colour = datalabels.colour,
          datalabels.colour_fill = datalabels.colour_fill,
          datalabels.size = datalabels.size,
          datalabels.angle = datalabels.angle,
          datalabels.lineheight = datalabels.lineheight,
          decimal.mark = decimal.mark,
          big.mark = big.mark,
          summarise_function = summarise_function,
          stacked = stacked,
          stackedpercent = stackedpercent,
          horizontal = horizontal,
          reverse = reverse,
          smooth = smooth,
          smooth.method = smooth.method,
          smooth.formula = smooth.formula,
          smooth.se = smooth.se,
          smooth.level = smooth.level,
          smooth.alpha = smooth.alpha,
          smooth.linewidth = smooth.linewidth,
          smooth.linetype = smooth.linetype,
          smooth.colour = smooth.colour,
          # size = size,
          linetype = linetype,
          linewidth = linewidth,
          binwidth = binwidth,
          width = width,
          jitter_seed = jitter_seed,
          violin_scale = violin_scale,
          legend.position = legend.position,
          legend.title = legend.title,
          legend.reverse = legend.reverse,
          legend.barheight = legend.barheight,
          legend.barwidth = legend.barwidth,
          legend.nbin = legend.nbin,
          legend.italic = legend.italic,
          sankey.node_width = sankey.node_width,
          sankey.node_whitespace = sankey.node_whitespace,
          sankey.alpha = sankey.alpha,
          sankey.remove_axes = sankey.remove_axes,
          zoom = zoom,
          sep = sep,
          print = print,
          text_factor = text_factor,
          font = font,
          theme = theme,
          background = background,
          markdown = markdown,
          
          `_misses.x` = FALSE,
          `_misses.y` = FALSE,
          `_misses.category` = FALSE,
          `_misses.facet` = missing(facet),
          `_misses.datalabels` = missing(datalabels),
          `_misses.colour_fill` = missing(colour_fill),
          `_misses.x.title` = FALSE,
          `_misses.y.title` = FALSE,
          `_misses.title` = FALSE,
          `_misses.subtitle` = missing(subtitle),
          `_misses.tag` = missing(tag),
          `_misses.caption` = FALSE,
          `_misses.y.percent` = missing(y.percent),
          `_misses.y.percent_break` = missing(y.percent_break),
          `_misses.x.zoom` = missing(x.zoom),
          `_misses.x.max_items` = missing(x.max_items),
          `_misses.facet.fixed_x` = missing(facet.fixed_x),
          `_label.x` = deparse(substitute(x)),
          `_label.y` = deparse(substitute(y)),
          `_label.category` = deparse(substitute(category)),
          `_label.facet` = deparse(substitute(facet)),
          `_label.y_secondary` = deparse(substitute(y_secondary)),
          `_summarise_fn_name` = deparse(substitute(summarise_function)),
          `_misses.summarise_function` = missing(summarise_function),
          ...) %>%
    add_line(y = moving_avg,
             data = .$data |> filter(period_txt %like% "Periode 0:"),
             colour = colour[1],
             linewidth = 0.6,
             inherit.aes = FALSE) %>%
    (function(x) {
      if ("moving_avg_limit" %in% x$data) {
        x |> add_line(y = moving_avg_limit,
                      colour = colour[1],
                      linetype = 2,
                      linewidth = 0.6,
                      inherit.aes = FALSE)
      } else {
        x
      }})() |> 
    add_type(data = clusters,
             type = "rect",
             mapping = aes(xmin = xmin,
                           xmax = xmax,
                           ymin = 0,
                           ymax = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.05),
             fill = get_colour(colour[1]),
             alpha = 0.1,
             inherit.aes = FALSE) |> 
    move_layer(move = -99) |> 
    # arrow left to right (arrow head on the right)
    add_type(data = clusters,
             type = "segment",
             mapping = aes(x = xmin,
                           xend = xmax,
                           y = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.05,
                           yend = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.05),
             lineend = "round",
             linejoin = "round",
             arrow = grid::arrow(angle = 90, length = unit(2, "pt")),
             colour = get_colour(colour[1]),
             linewidth = 0.5,
             inherit.aes = FALSE) |> 
    # arrow right to left (arrow head on the left)
    add_type(data = clusters,
             type = "segment",
             mapping = aes(x = xmax,
                           xend = xmin,
                           y = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.05,
                           yend = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.05),
             lineend = "round",
             linejoin = "round",
             arrow = grid::arrow(angle = 90, length = unit(2, "pt")),
             colour = get_colour(colour[1]),
             linewidth = 0.5,
             inherit.aes = FALSE) |> 
    # arrow right to left (arrow head on the left)
    add_type(data = clusters,
             type = "text",
             mapping = aes(label = paste0("N = ", n_cases),
                           x = xmax - (xmax - xmin) / 2,
                           y = max(early_warning_object$details$moving_avg, na.rm = TRUE) * 1.1),
             colour = get_colour(colour[1]),
             size = datalabels.size,
             fontface = "bold",
             inherit.aes = FALSE)
  
  if (isTRUE(attributes(early_warning_object)$based_on_historic_maximum)) {
    p <- p |>
      add_line(y = moving_avg_max,
               data = p$data |> mutate(period_txt = "Maximum"),
               linewidth = 0.5,
               inherit.aes = FALSE)
  }
  
  if (isTRUE(print)) {
    print(p)
  } else {
    p
  }
}
